### PR TITLE
Fix for #16

### PR DESCRIPTION
**Pull request by jkutner**
This is what i'm proposing we add to support an optional jsvc user arg

see #16

### CODE REVIEW

**Comment by kares** [comment]
well, the -user option was there previously ... before $RUN_USER was introduced :)
now it might get slightly confusing having 2 $USER variables in the script (or maybe not ?) ... at least it should be documented that they are intended to be used mutually exclusive.

**Comment by calavera** [comment]
I agree with @kares, we should document this better.

**Comment by jkutner** [comment]
I could make the $JSVC_USER a bool flag, and set `-user $RUN_USER` or `-user $USER` accordingly.  

and yes, i will definitely document it

**Comment by jkutner** [comment]
is this better?  i'll add some notes to the README, too.

**Comment by calavera** [comment]
it looks good to me, @kares?

**Comment by jkutner** [comment]
documentation added.  waiting for @kares blessing before merging.

**Comment by kares** [comment]
@jkutner :) no need to wait for me unless you tested it and it's fine ...
I still do not get the point of your current `jsvc -user $USER` way, isn't it the same as running without the -user option ? 
I thought it's for cases when the script is init-ed with root rights to "sudo" that's why I changed it since it did not work :(
But as I said anything that suits you, I'm not using it anyways or I change the script manually if you force me to :) ...

**Comment by jkutner** [comment]
I'm an idiot. i just realized a better way to do this:

JSVC_ARGS_EXTRA="-user myuser" /etc/init.d/trinidad start

I'll just document that instead of merging this pull since it's a "second-class" way of doing things.

@kares yea, i don't get why i need it either. SWAG: because i don't have capabilities enabled i think it just won't run without the `-user` option.

:P

**Comment by kares** [comment]
heh, well maybe it's not that of a second-class after all maybe I was doing smt wrong that -user did not work me ...
if we get another report on this I guess it's perfectly valid to somehow revert #12 and have `jsvc -user` first-class and the "sudo" workaround second-class if possible (or documented).

**Comment by jkutner** [comment]
i added a description at the bottom here:
https://github.com/trinidad/trinidad_init_services/blob/master/README

yea, let's wait and see if anyone else has issues.

**Pull request closed without merging**
