### PR TITLE
Check to see if the process in the pid file is actually running and if it's the name that we expect

### PR DESCRIPTION
**Pull request by w1150n**
This is to make the trinidad service start after the machine was halted and restarted.

https://github.com/trinidad/trinidad_init_services/issues/34

### CODE REVIEW

**Comment by arturtr** [comment]
What about this pull request?

Or maybe this project is not supported and there is some alternative?

**Comment by kares** [comment]
First of all thank you Mather for this - seems quite useful. It sure needs to get in.
@arturtr I somehow missed this one, I would be interested in knowing if you've tested @w1150n's commit and what env / OS did you try it, thank you.

**Comment by arturtr** [comment]
I want to try it on ubuntu 12.04 with jRuby, but i don't know how to install gem directly from github source

**Comment by kares** [comment]
hmm, and why is using the gem as it is and changing the lines in the generated init.d script accordingly an issue ?

**Comment by arturtr** [comment]
I just try to use trinidad for use it with jruby by railscast instuction - http://railscasts.com/episodes/377-trinidad

Today our server was reboot and I catch this bug #34 
Then I found pull request which solving this bug and wanted to know about its fate

**Comment by kares** [comment]
it's fate is that I'll merge it but can not test it out really now ... thus I was hoping someone would test the changes out ...

**Comment by arturtr** [comment]
I found this gem fir install from repo - https://github.com/rdp/specific_install

Now I'll try to test pull request

**Comment by arturtr** [comment]
I checked it on Ubuntu 12.04 x64 and it works!

After reboot trinidad service was started well

**Comment by kares** [comment]
@arturtr thank you for testing this out ... just released 1.2.3 hope it will work great for you!

**Comment by arturtr** [comment]
Thank you @kares

**Pull request merged**
