### PR TITLE
jsvc compiling on *nix (except darwin)

### PR DESCRIPTION
**Pull request by kares**
hey guys, I'm looking for a review here ... to check what I'm doing is acceptable.

looking into #6 turns out there's a yet another `jsvc` issue, now instead of compiling and bundling yet another x64 binary (that might not work for everybody) I was thinking of compiling jsvc from source on demand (since users are obviously lazy to do so - none of the 2 reporters tried it out in a month) ...

thus there's no `jsvc_linux` bundled anymore, instead :
1. user provides a jsvc_path in the config
2. installs jsvc using package manager and it will be detect if on the PATH (`which jsvc`)
3. jsvc is "extracted" into a user provided location and compiled

there's a warning about `gcc` needed to be installed.

if no objections are raised I shall release a new version ...

### CODE REVIEW

**Comment by jkutner** [comment]
I'll take a look tonight.  my initial concern is that this method won't work on windows:

```
 def detect_jsvc_path
   jsvc_path = `which jsvc` # "/usr/bin/jsvc\n"
   jsvc_path.chomp!
   jsvc_path.empty? ? bundled_jsvc_path : jsvc_path
 end
```

Though i have never tried trinidad_init_service on windows.

**Comment by kares** [comment]
@jkutner all `jsvc` crap is only used with *nixes and thus only called from `configure_unix_daemon`

**Comment by jkutner** [comment]
Oh i see.  and you are still including the Windows jsvc?  that's cool.

**Comment by kares** [comment]
there's no jsvc on Windows it's called slightly different - **prunsrv** - does about the same job.
actually there still pre-compiled `jsvc_darwin` since I have not tested on Mac + there were no complains for OSX :)

**Comment by calavera** [comment]
Sounds good to me. @kares can you add information about this in the readme?

**Comment by jkutner** [comment]
I get this error when running `jruby -S trinidad_init_services` (I built the gem from your fork).

```
checking for JDK os include directory... Cannot find jni_md.h in /usr/lib/jvm/java-6-openjdk/jre/
RuntimeError: `cd /usr/local/src/jsvc-unix-src && ./configure --with-java=/usr/lib/jvm/java-6-openjdk/jre` failed with status: 1
           compile_jsvc at /opt/jruby-1.6.7/lib/ruby/gems/1.8/gems/trinidad_init_services-1.1.3/lib/trinidad_init_services/configuration.rb:181
  configure_unix_daemon at /opt/jruby-1.6.7/lib/ruby/gems/1.8/gems/trinidad_init_services-1.1.3/lib/trinidad_init_services/configuration.rb:64
              configure at /opt/jruby-1.6.7/lib/ruby/gems/1.8/gems/trinidad_init_services-1.1.3/lib/trinidad_init_services/configuration.rb:54
                 (root) at /opt/jruby-1.6.7/lib/ruby/gems/1.8/gems/trinidad_init_services-1.1.3/bin/trinidad_init_service:10
                   load at org/jruby/RubyKernel.java:1058
                 (root) at /opt/jruby/bin/trinidad_init_service:19
```

Other info:

```
$ uname -a
Linux lucid64 2.6.32-33-server #70-Ubuntu SMP Thu Jul 7 22:28:30 UTC 2011 x86_64 GNU/Linux
$ java -version
java version "1.6.0_20"
OpenJDK Runtime Environment (IcedTea6 1.9.10) (6b20-1.9.10-0ubuntu1~10.04.3)
OpenJDK 64-Bit Server VM (build 19.0-b09, mixed mode)
```

**Comment by jkutner** [comment]
After running `apt-get install jsvc` it seemed to work fine. No need to add jsvc_path.   I like that! 

Given that, I think it's still okay to merge it.  It's unlikely that building from source will work on every environment, and it seems to work well otherwise.  

One little change, this statement in the prompt:

```
path to jsvc binary (leave blank and we're try to compile)?  
```

Should be:

```
path to jsvc binary (leave blank and we'll try to compile)?  
```

**Comment by kares** [comment]
Thanks a lot Joe, I'll change the prompt.

The failure you observed is due to pointing to a JRE not JDK: `System.getProperty("java.home")` works that way.
I'm aware of that and was thinking of adding a warning as it fails. 
I'll improve the detection if it's a "/jre" path within a JDK ... since users might be hitting the same failure a lot.

**Pull request merged**
