### PR TITLE
Fix issue on with -errfile &1 being misinterpreted.

### PR DESCRIPTION
**Pull request by boxofrad**
This commit fixes a weird issue i've been having where the `&1` JSVC option would appear to be interpreted as:

Background the process `&` and run `1`

And would return the following ouput:

```
[1] 992
Invalid Error File specified
Cannot parse command line arguments
1: command not found
```

This issue is present on Ubuntu 10.04 LTS and bash version 4.1.5(1).

### CODE REVIEW

**Comment by calavera** [comment]
Thank you!! I'm releasing a new version of the gem with you patch right away.

**Comment by tolsen** [comment]
I'm having this issue now.  The fix appears to have been reverted in c532ef5cdc25f35f2e22e0b1de09eb317b9566ab

**Comment by tolsen** [comment]
btw, I am also using Ubuntu 10.04 LTS with bash version 4.1.5(1)

**Comment by tolsen** [comment]
The problem appears to have mysteriously gone away.  Not sure why, but I'll let you know if I find out!

**Comment by tolsen** [comment]
Ok.  I think the problem is that I was running the full jsvc command by hand to debug a different problem.  When run directly, you must put single quotes around &1.  But when placed inside an environment variable (such as START_COMMAND in init.d/trinidad) and run through the environment variable, &1 is automatically escaped.

**Pull request merged**
